/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroswing.telas;

/**
 *
 * @author 69146
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTRecebeNome = new javax.swing.JTextField();
        jCMarcas = new javax.swing.JComboBox<>();
        jLMarcas = new javax.swing.JLabel();
        jLReceMarca = new javax.swing.JLabel();
        jLHeader = new javax.swing.JLabel();
        jCFiltrarPesquisa = new javax.swing.JCheckBox();
        jLCheckBox = new javax.swing.JLabel();
        jLGroupRadio = new javax.swing.JLabel();
        jRMaculino = new javax.swing.JRadioButton();
        jRFeminino = new javax.swing.JRadioButton();
        jLResultadoFiltro = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setResizable(false);

        jLabel1.setText("Informe um nome");

        jTNome.setName(""); // NOI18N

        jButton1.setText("Clique aqui");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jTRecebeNome.setEditable(false);
        jTRecebeNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRecebeNomeActionPerformed(evt);
            }
        });

        jCMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ford", "Fiat", "Toyota", "Volkswagen", "Mercedes", "Hyundai" }));
        jCMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMarcasActionPerformed(evt);
            }
        });

        jLMarcas.setText("Marcas ComboBox");

        jLReceMarca.setForeground(new java.awt.Color(255, 0, 0));

        jLHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLHeader.setText("Componentes ques usamos em formulário");

        jCFiltrarPesquisa.setText("Pesquisar todos?");
        jCFiltrarPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFiltrarPesquisaActionPerformed(evt);
            }
        });

        jLCheckBox.setText("CheckBox");

        jLGroupRadio.setText("Radio Button");

        buttonGroup1.add(jRMaculino);
        jRMaculino.setText("Masculino");
        jRMaculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMaculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRFeminino);
        jRFeminino.setText("Feminino");
        jRFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFemininoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRFeminino)
                    .addComponent(jLGroupRadio)
                    .addComponent(jRMaculino)
                    .addComponent(jLHeader)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTRecebeNome)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(jTNome))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLMarcas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLReceMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCFiltrarPesquisa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLResultadoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMarcas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLReceMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRecebeNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGroupRadio)
                    .addComponent(jCFiltrarPesquisa)
                    .addComponent(jLResultadoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRMaculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRFeminino)
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTRecebeNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRecebeNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRecebeNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTRecebeNome.setText(jTNome.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jCMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMarcasActionPerformed
        int selected = jCMarcas.getSelectedIndex();
        jLReceMarca.setText(jCMarcas.getItemAt(selected));
    }//GEN-LAST:event_jCMarcasActionPerformed

    private void jCFiltrarPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFiltrarPesquisaActionPerformed
        if (jCFiltrarPesquisa.isSelected()){
            jLResultadoFiltro.setText("Sim");
        }else{
            jLResultadoFiltro.setText("Não");
        }
    }//GEN-LAST:event_jCFiltrarPesquisaActionPerformed

    private void jRMaculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMaculinoActionPerformed
        if (jRMaculino.isSelected())
            jLGroupRadio.setText((jRMaculino.getText()));
    }//GEN-LAST:event_jRMaculinoActionPerformed

    private void jRFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFemininoActionPerformed
        if (jRFeminino.isSelected())
            jLGroupRadio.setText((jRFeminino.getText()));
    }//GEN-LAST:event_jRFemininoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCFiltrarPesquisa;
    private javax.swing.JComboBox<String> jCMarcas;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLCheckBox;
    private javax.swing.JLabel jLGroupRadio;
    private javax.swing.JLabel jLHeader;
    private javax.swing.JLabel jLMarcas;
    private javax.swing.JLabel jLReceMarca;
    private javax.swing.JLabel jLResultadoFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRFeminino;
    private javax.swing.JRadioButton jRMaculino;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTRecebeNome;
    // End of variables declaration//GEN-END:variables
}
