/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import agenda.controller.ControllerGeral;
import agenda.modelo.Contato;
import javax.swing.JOptionPane;

/**
 *
 * @author 69146
 */
public class CadastroContato extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContato
     */
    //ControllerGeral controller = new ControllerGeral();
    
    public CadastroContato() {
        initComponents();
    }
    
    private boolean validaEmpty(){
        if (jTFNome.getText().equals("") || jTFNome.getText().startsWith(" ")){
            JOptionPane.showMessageDialog(rootPane, "Nome não informado");
            jTFNome.requestFocus();
            return false;
        }else if (jTFEmail.getText().equals("") || jTFEmail.getText().startsWith(" ")){
            JOptionPane.showMessageDialog(rootPane, "Email não informado");
            jTFEmail.requestFocus();
            return false;
        }else if (jFTFFone.getText().trim().length() != 16){
            JOptionPane.showMessageDialog(rootPane, "Fone não informado");
            jFTFFone.requestFocus();
            return false;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Contato inserido com sucesso");
            return true;
        }
    }
    
    private void limpar(){
        jTFNome.setText("");
        jTFEmail.setText("");
        jFTFFone.setText("");
        jTFNome.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBcadastroSalvar = new javax.swing.JButton();
        jBcadastroCancelar = new javax.swing.JButton();
        jFTFFone = new javax.swing.JFormattedTextField();
        jTFEmail = new javax.swing.JTextField();

        jLabel1.setText("Nome");

        jLabel2.setText("Email");

        jLabel3.setText("Fone");

        jBcadastroSalvar.setText("Salvar");
        jBcadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastroSalvarActionPerformed(evt);
            }
        });

        jBcadastroCancelar.setText("Cancelar");
        jBcadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastroCancelarActionPerformed(evt);
            }
        });

        try {
            jFTFFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFFoneActionPerformed(evt);
            }
        });

        jTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jTFNome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBcadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jBcadastroCancelar))
                    .addComponent(jFTFFone)
                    .addComponent(jTFEmail))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcadastroCancelar)
                    .addComponent(jBcadastroSalvar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastroSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTFNome.getText();
        String email = jTFEmail.getText();
        String fone = jFTFFone.getText();
        
        Contato ct = new Contato(nome, email, fone);
        
        //ControllerGeral controller = new ControllerGeral();
        ControllerGeral.contatos.add(ct);
        //controller.listarContatos();
        
        //System.out.println(ct.toString());
        
        boolean validade = validaEmpty();
        if (validade == true){
            limpar();
            if (ct.salvar()){
                limpar();
            }else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar contato");
            }
        }
    }//GEN-LAST:event_jBcadastroSalvarActionPerformed

    private void jBcadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastroCancelarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jBcadastroCancelarActionPerformed

    private void jTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailActionPerformed

    private void jFTFFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFFoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastroCancelar;
    private javax.swing.JButton jBcadastroSalvar;
    private javax.swing.JFormattedTextField jFTFFone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
